"""Cookie file generator — converts Chrome cookie objects to Netscape format.

Receives an array of Chrome cookie objects from the extension and writes
a strictly formatted Netscape HTTP Cookie File that yt-dlp reads natively
via the ``cookiefile`` option. This bypasses YouTube's anti-bot detection
(which rejects raw Cookie headers) while avoiding the multi-second latency
of ``cookiesfrombrowser`` SQLite decryption on low-end hardware.
"""

from __future__ import annotations

import logging
import os
import tempfile
from typing import Any

from src.config import settings

logger = logging.getLogger(__name__)

# Persistent temp directory inside the project data dir
_COOKIE_DIR: str | None = None


def _ensure_cookie_dir() -> str:
    """Create and return the cookie temp directory."""
    global _COOKIE_DIR
    if _COOKIE_DIR is None:
        _COOKIE_DIR = os.path.join(os.path.abspath(settings.download_dir), ".thunder_cookies")
        os.makedirs(_COOKIE_DIR, exist_ok=True)
    return _COOKIE_DIR


def cookies_to_netscape(cookies: list[dict[str, Any]]) -> str:
    """Convert a list of Chrome cookie objects to Netscape cookie file content.

    Each cookie object should have at minimum:
        - domain (str)
        - name (str)
        - value (str)

    Optional fields (with sensible defaults):
        - path (str, default "/")
        - secure (bool, default False)
        - httpOnly (bool, default False)
        - expirationDate (float, default 0)
    """
    lines = ["# Netscape HTTP Cookie File", "# Generated by Thunder daemon", ""]

    for c in cookies:
        domain = c.get("domain", "")
        if not domain or not c.get("name"):
            continue

        # Netscape format: domain flag path secure expiry name value
        # flag = TRUE if domain starts with "." (domain-wide cookie)
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expiry = str(int(c.get("expirationDate", 0)))
        name = c.get("name", "")
        value = c.get("value", "")

        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")

    return "\n".join(lines) + "\n"


def write_cookie_file(cookies: list[dict[str, Any]]) -> str | None:
    """Write cookies to a temp file and return the path.

    Returns None if cookies list is empty or invalid.
    The file is written atomically to prevent partial reads.
    """
    if not cookies:
        return None

    content = cookies_to_netscape(cookies)

    cookie_dir = _ensure_cookie_dir()
    fd, path = tempfile.mkstemp(prefix="thunder_", suffix=".txt", dir=cookie_dir)
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
    except Exception:
        logger.warning("Failed to write cookie file", exc_info=True)
        try:
            os.unlink(path)
        except OSError:
            pass
        return None

    return path


def cleanup_cookie_file(path: str | None) -> None:
    """Remove a temporary cookie file after use."""
    if path is None:
        return
    try:
        os.unlink(path)
    except OSError:
        pass
